export default {
  gameWord: [
    {
      id: 1,
      word: 'FRAME',
      hint: 'You put an photograph here ?',
      isComplete: false,
      description: `a border of wood or metal that goes around the outside of a door, picture, window, etc.`,
    },
    {
      id: 2,
      word: 'WATER',
      hint: 'Two hydrogen and one Oxygen?',
      isComplete: false,
      description: '',
    },
    {
      id: 3,
      word: 'RIGHT',
      hint: 'Father is always right so word is ?',
      isComplete: false,
      description: '',
    },
    {
      id: 4,
      word: 'WRONG',
      hint: 'Say sorry when you are wrong',
      isComplete: false,
      description: '',
    },
    {
      id: 5,
      word: 'FRAME',
      hint: 'You put an photograph here',
      isComplete: false,
      description: `a border of wood or metal that goes around the outside of a door, picture, window, etc.`,
    },
    {
      id: 6,
      word: 'WATER',
      hint: 'Two hydrogen and one Oxygen',
      isComplete: false,
      description: '',
    },
    {
      id: 7,
      word: 'RIGHT',
      hint: 'Father is always right so word is',
      isComplete: false,
      description: '',
    },
    {
      id: 8,
      word: 'WRONG',
      hint: 'Say sorry when you are wrong',
      isComplete: false,
      description: '',
    },
    {
      id: 9,
      word: 'FRAME',
      hint: 'You put an photograph here',
      isComplete: false,
      description: `a border of wood or metal that goes around the outside of a door, picture, window, etc.`,
    },
    {
      id: 10,
      word: 'WATER',
      hint: 'Two hydrogen and one Oxygen',
      isComplete: false,
      description: '',
    },
    {
      id: 11,
      word: 'RIGHT',
      hint: 'Father is always right so word is',
      isComplete: false,
      description: '',
    },
    {
      id: 12,
      word: 'WRONG',
      hint: 'Say sorry when you are wrong',
      isComplete: false,
      description: '',
    },
    {
      id: 13,
      word: 'FRAME',
      hint: 'You put an photograph here',
      isComplete: false,
      description: `a border of wood or metal that goes around the outside of a door, picture, window, etc.`,
    },
    {
      id: 14,
      word: 'WATER',
      hint: 'Two hydrogen and one Oxygen',
      isComplete: false,
      description: '',
    },
    {
      id: 15,
      word: 'RIGHT',
      hint: 'Father is always right so word is',
      isComplete: false,
      description: '',
    },
    {
      id: 16,
      word: 'WRONG',
      hint: 'Say sorry when you are wrong',
      isComplete: false,
      description: '',
    },
  ],

  gameData: [
    {word: '', color: '', disable: false},
    {word: '', color: '', disable: false},
    {word: '', color: '', disable: false},
    {word: '', color: '', disable: false},
    {word: '', color: '', disable: false},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
    {word: '', color: '', disable: true},
  ],
};
